services:
  nodejs-server:
    image: happysingh2005/chaicode-node
    deploy:
      replicas: 4
    networks:
      - chaicode-internal

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - chaicode-internal

networks:
  chaicode-internal:
  driver: bridge
